### ISSUE TITLE
path in account

### ISSUE THREAD

**Issue by adrian-cytrix** [clansofts/dea#1]
Hello, Can i ask what is path in Account Table?

**Comment by clansofts** [comment]
Hi @adrian-cytrix . Mostly when dealing with a chart of account you would have parent - child relationship. so path field is to have something like say 'Assets/CCE/Checking' or 'Revenue/Sales/PowerPump' so that when querying you can decide to get a path like say 'Assets/CCE' and it pulls all accounts under that path.

**Comment by clansofts** [comment]
Hi @adrian-cytrix . Mostly when dealing with a chart of account you would have parent - child relationship. so path field is to have something like say 'Assets/CCE/Checking' or 'Revenue/Sales/PowerPump' so that when querying you can decide to get a path like say 'Assets/CCE' and it pulls all accounts under that path.
